name: Nexus3
description: |
  A repository manager.
version: 3.0.2-02
category: Continuous Integration
maintainer: Grant Zukel admin@idevops.io
license: Apache2
projectURL: http://automation.gmacon.solutions:10080/idevops/OPENLDAP365
