nexus:
  image: sonatype/nexus3:latest
    - 8081:8081/tcp
  volumes_from:
    - nexus3-datavolume
  labels:
    io.rancher.sidekicks: nexus3-datavolume
    io.rancher.container.hostname_override: container_name
  environment:
    MAX_HEAP: 768m
nexus3-datavolume:
  image: "busybox"
  command: chown -R 200 /sonatype-work
  volumes:
    - /sonatype-work
  labels:
    io.rancher.container.start_once: true
